- job:
    name: devstack-plugin-container-dsvm
    parent: legacy-dsvm-base
    run: playbooks/devstack-plugin-container-dsvm/run.yaml
    post-run: playbooks/devstack-plugin-container-dsvm/post.yaml
    timeout: 4200
    required-projects:
      - openstack/devstack
      - openstack/devstack-gate
      - openstack/devstack-plugin-container

- project:
    check:
      jobs:
        - devstack-plugin-container-dsvm
    gate:
      jobs:
        - devstack-plugin-container-dsvm
