- job:
    name: devstack-plugin-container-dsvm
    parent: devstack
    pre-run: playbooks/devstack-plugin-container-dsvm/pre.yaml
    run: playbooks/devstack-plugin-container-dsvm/run.yaml
    post-run: playbooks/devstack-plugin-container-dsvm/post.yaml
    timeout: 4200
    required-projects:
      - openstack/devstack
      - openstack/devstack-gate
      - openstack/devstack-plugin-container
    vars:
      devstack_localrc:
        USE_PYTHON3: true
      devstack_plugins:
        devstack-plugin-container: https://opendev.org/openstack/devstack-plugin-container

- project:
    check:
      jobs:
        - devstack-plugin-container-dsvm
    gate:
      jobs:
        - devstack-plugin-container-dsvm
