- hosts: all
  name: Verify that Docker is installed correctly by running the hello-world image
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          sudo -H -u stack docker run hello-world
